-- ===============================================
-- Call Center Demo DDL
-- Customers, Products, Orders, Call Transcripts
-- ===============================================

CREATE DATABASE IF NOT EXISTS CALL_CENTER;
CREATE SCHEMA IF NOT EXISTS CALL_CENTER.STG;
USE SCHEMA CALL_CENTER.STG;

CREATE STAGE IF NOT EXISTS CALL_CENTER.STG.TRANSCRIPTS;

-- Customers Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.CUSTOMERS (
    CUSTOMER_ID                 VARCHAR(50)     NOT NULL,
    FIRST_NAME                  VARCHAR(100)    NOT NULL,
    LAST_NAME                   VARCHAR(100)    NOT NULL,
    EMAIL                       VARCHAR(200),
    PHONE                       VARCHAR(20),
    ADDRESS_LINE_1              VARCHAR(200),
    CITY                        VARCHAR(100),
    STATE                       VARCHAR(50),
    ZIP_CODE                    VARCHAR(20),
    LOYALTY_TIER                VARCHAR(20)     DEFAULT 'STANDARD',
    CREATED_AT                  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (CUSTOMER_ID)
);

-- Products Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.PRODUCTS (
    PRODUCT_ID                  VARCHAR(50)     NOT NULL,
    PRODUCT_NAME                VARCHAR(200)    NOT NULL,
    SKU                         VARCHAR(50)     NOT NULL,
    CATEGORY                    VARCHAR(100),
    PRICE                       NUMBER(10,2)    NOT NULL,
    DESCRIPTION                 VARCHAR(1000),
    IN_STOCK                    BOOLEAN         DEFAULT TRUE,
    CREATED_AT                  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (PRODUCT_ID),
    UNIQUE (SKU)
);

-- Orders Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.ORDERS (
    ORDER_ID                    VARCHAR(50)     NOT NULL,
    ORDER_NUMBER                VARCHAR(50)     NOT NULL,
    CUSTOMER_ID                 VARCHAR(50)     NOT NULL,
    ORDER_DATE                  DATE            NOT NULL,
    ORDER_STATUS                VARCHAR(30)     DEFAULT 'PENDING',
    SHIPPING_ADDRESS            VARCHAR(500),
    SHIPPING_METHOD             VARCHAR(50),
    TRACKING_NUMBER             VARCHAR(100),
    SUBTOTAL                    NUMBER(12,2),
    TAX                         NUMBER(10,2),
    SHIPPING_COST               NUMBER(10,2),
    TOTAL                       NUMBER(12,2),
    NOTES                       VARCHAR(1000),
    CREATED_AT                  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT                  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (ORDER_ID),
    UNIQUE (ORDER_NUMBER),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CALL_CENTER.STG.CUSTOMERS(CUSTOMER_ID)
);

-- Order Items Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.ORDER_ITEMS (
    ORDER_ITEM_ID               VARCHAR(50)     NOT NULL,
    ORDER_ID                    VARCHAR(50)     NOT NULL,
    PRODUCT_ID                  VARCHAR(50)     NOT NULL,
    QUANTITY                    INTEGER         NOT NULL DEFAULT 1,
    UNIT_PRICE                  NUMBER(10,2)    NOT NULL,
    LINE_TOTAL                  NUMBER(12,2)    NOT NULL,
    CREATED_AT                  TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES CALL_CENTER.STG.ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES CALL_CENTER.STG.PRODUCTS(PRODUCT_ID)
);

-- Call Transcripts Table
CREATE OR REPLACE TABLE CALL_CENTER.STG.CALL_TRANSCRIPTS (
    ID                          NUMBER(38,0)    NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CASE_ID                     VARCHAR(255)    NOT NULL,
    CALL_ID                     VARCHAR(255)    NOT NULL,
    TRANSCRIPT                  VARCHAR(16777216) NOT NULL,
    CHUNK_NUMBER                NUMBER(38,0),
    CHUNK_START_TIME            TIMESTAMP_NTZ(9),
    CHUNK_END_TIME              TIMESTAMP_NTZ(9),
    CHUNK_DURATION_SECONDS      NUMBER(10,3),
    SESSION_START_TIME          TIMESTAMP_NTZ(9),
    CONFIDENCE_SCORE            NUMBER(5,2),
    CREATED_AT                  TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (ID)
);

-- Call Candidate Values Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.CALL_CANDIDATE_VALUES (
    ID                          NUMBER(38,0)    NOT NULL AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    CASE_ID                     VARCHAR(255)    NOT NULL,
    CALL_ID                     VARCHAR(255)    NOT NULL,
    FIELD_NAME                  VARCHAR(255)    NOT NULL,
    CANDIDATE_VALUE             VARCHAR(16777216) NOT NULL,
    CONFIDENCE_SCORE            NUMBER(5,2),
    CONTEXT_TRANSCRIPT          VARCHAR(16777216) NOT NULL,
    TRANSCRIPT_TIMESTAMP        TIMESTAMP_NTZ(9) NOT NULL,
    IS_SELECTED                 BOOLEAN         DEFAULT FALSE,
    SELECTED_BY                 VARCHAR(255),
    SELECTED_AT                 TIMESTAMP_NTZ(9),
    CREATED_AT                  TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (ID),
    INDEX IDX_CASE_CANDIDATE(CASE_ID),
    INDEX IDX_FIELD_CANDIDATE(FIELD_NAME),
    INDEX IDX_SELECTED(IS_SELECTED)
);

-- Cases Table
CREATE OR REPLACE HYBRID TABLE CALL_CENTER.STG.CASES (
    CASE_ID             VARCHAR(50)     NOT NULL,
    CASE_NUMBER         VARCHAR(50)     NOT NULL,
    CUSTOMER_ID         VARCHAR(50)     NOT NULL,
    ORDER_ID            VARCHAR(50),
    PRODUCT_ID          VARCHAR(50),
    CASE_TYPE           VARCHAR(50)     NOT NULL,
    CASE_STATUS         VARCHAR(30)     DEFAULT 'OPEN',
    PRIORITY            VARCHAR(20)     DEFAULT 'MEDIUM',
    SUBJECT             VARCHAR(500)    NOT NULL,
    DESCRIPTION         VARCHAR(4000),
    RESOLUTION          VARCHAR(4000),
    OPENED_AT           TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),
    CLOSED_AT           TIMESTAMP_NTZ,
    UPDATED_AT          TIMESTAMP_NTZ   DEFAULT CURRENT_TIMESTAMP(),

    PRIMARY KEY (CASE_ID),
    UNIQUE (CASE_NUMBER),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CALL_CENTER.STG.CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES CALL_CENTER.STG.ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES CALL_CENTER.STG.PRODUCTS(PRODUCT_ID),
    INDEX IDX_CASES_CUSTOMER(CUSTOMER_ID),
    INDEX IDX_CASES_PRODUCT(PRODUCT_ID),
    INDEX IDX_CASES_STATUS(CASE_STATUS),
    INDEX IDX_CASES_TYPE(CASE_TYPE)
);

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_EMAIL ON CALL_CENTER.STG.CUSTOMERS(EMAIL);
CREATE INDEX IF NOT EXISTS IDX_CUSTOMERS_PHONE ON CALL_CENTER.STG.CUSTOMERS(PHONE);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_CUSTOMER ON CALL_CENTER.STG.ORDERS(CUSTOMER_ID);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_NUMBER ON CALL_CENTER.STG.ORDERS(ORDER_NUMBER);
CREATE INDEX IF NOT EXISTS IDX_ORDERS_STATUS ON CALL_CENTER.STG.ORDERS(ORDER_STATUS);
CREATE INDEX IF NOT EXISTS IDX_ORDER_ITEMS_ORDER ON CALL_CENTER.STG.ORDER_ITEMS(ORDER_ID);
CREATE INDEX IF NOT EXISTS IDX_PRODUCTS_SKU ON CALL_CENTER.STG.PRODUCTS(SKU);

-- Summary Views
CREATE OR REPLACE VIEW CALL_CENTER.STG.V_CUSTOMER_ORDERS AS
SELECT
    c.CUSTOMER_ID,
    c.FIRST_NAME,
    c.LAST_NAME,
    c.EMAIL,
    c.PHONE,
    o.ORDER_NUMBER,
    o.ORDER_DATE,
    o.ORDER_STATUS,
    o.TOTAL,
    o.TRACKING_NUMBER
FROM CALL_CENTER.STG.CUSTOMERS c
JOIN CALL_CENTER.STG.ORDERS o ON c.CUSTOMER_ID = o.CUSTOMER_ID
ORDER BY o.ORDER_DATE DESC;

CREATE OR REPLACE VIEW CALL_CENTER.STG.V_ORDER_DETAILS AS
SELECT
    o.ORDER_NUMBER,
    o.ORDER_STATUS,
    o.ORDER_DATE,
    c.FIRST_NAME || ' ' || c.LAST_NAME AS CUSTOMER_NAME,
    c.EMAIL AS CUSTOMER_EMAIL,
    c.PHONE AS CUSTOMER_PHONE,
    p.PRODUCT_NAME,
    p.SKU,
    oi.QUANTITY,
    oi.UNIT_PRICE,
    oi.LINE_TOTAL,
    o.TOTAL AS ORDER_TOTAL,
    o.TRACKING_NUMBER
FROM CALL_CENTER.STG.ORDERS o
JOIN CALL_CENTER.STG.CUSTOMERS c ON o.CUSTOMER_ID = c.CUSTOMER_ID
JOIN CALL_CENTER.STG.ORDER_ITEMS oi ON o.ORDER_ID = oi.ORDER_ID
JOIN CALL_CENTER.STG.PRODUCTS p ON oi.PRODUCT_ID = p.PRODUCT_ID;
CREATE OR REPLACE VIEW CALL_CENTER.STG.V_PRODUCT_ISSUES AS
SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.SKU,
    p.CATEGORY,
    COUNT(DISTINCT cs.CASE_ID) AS TOTAL_CASES,
    COUNT(DISTINCT cs.CUSTOMER_ID) AS AFFECTED_CUSTOMERS,
    COUNT(DISTINCT CASE WHEN cs.CASE_STATUS = 'OPEN' THEN cs.CASE_ID END) AS OPEN_CASES,
    MIN(cs.OPENED_AT) AS FIRST_REPORTED,
    MAX(cs.OPENED_AT) AS LAST_REPORTED,
    LISTAGG(DISTINCT cs.CASE_TYPE, ', ') WITHIN GROUP (ORDER BY cs.CASE_TYPE) AS ISSUE_TYPES,
    LISTAGG(DISTINCT cs.PRIORITY, ', ') WITHIN GROUP (ORDER BY cs.PRIORITY) AS PRIORITIES
FROM CALL_CENTER.STG.PRODUCTS p
JOIN CALL_CENTER.STG.CASES cs ON p.PRODUCT_ID = cs.PRODUCT_ID
GROUP BY p.PRODUCT_ID, p.PRODUCT_NAME, p.SKU, p.CATEGORY
ORDER BY TOTAL_CASES DESC;

COMMENT ON TABLE CALL_CENTER.STG.CASES IS 'Support cases linked to customers, orders, and products';
 'Customer information';
COMMENT ON TABLE CALL_CENTER.STG.PRODUCTS IS 'Product catalog';
COMMENT ON TABLE CALL_CENTER.STG.ORDERS IS 'Customer orders';
COMMENT ON TABLE CALL_CENTER.STG.ORDER_ITEMS IS 'Line items within orders';
COMMENT ON TABLE CALL_CENTER.STG.CALL_TRANSCRIPTS IS 'Audio transcriptions from call recordings';
COMMENT ON TABLE CALL_CENTER.STG.CALL_CANDIDATE_VALUES IS 'AI-extracted candidate values from call transcripts';
