-- ===============================================
-- Quilliam Cortex Search Service
-- Full meeting transcripts (chunk 0) searchable
-- ===============================================

USE ROLE ACCOUNTADMIN;
USE SCHEMA QUILLIAM.STG;

-- Grant required privileges
GRANT CREATE CORTEX SEARCH SERVICE ON SCHEMA QUILLIAM.STG TO ROLE QUILLIAM_ADMIN_RL;

-- Cortex Search Service on full transcripts
CREATE OR REPLACE CORTEX SEARCH SERVICE QUILLIAM.STG.MEETING_TRANSCRIPT_SEARCH
  ON TRANSCRIPT_TEXT
  ATTRIBUTES MEETING_ID
  WAREHOUSE = QUILLIAM_WH
  TARGET_LAG = '1 hour'
  AS (
    SELECT MEETING_ID, TRANSCRIPT_TEXT
    FROM QUILLIAM.STG.MEETING_TRANSCRIPTS
    WHERE CHUNK_NUMBER = 0
      AND TRANSCRIPT_TEXT IS NOT NULL
      AND LENGTH(TRIM(TRANSCRIPT_TEXT)) > 10
  );

GRANT USAGE ON CORTEX SEARCH SERVICE QUILLIAM.STG.MEETING_TRANSCRIPT_SEARCH TO ROLE QUILLIAM_ADMIN_RL;
