create or replace HYBRID TABLE FNOL_CANDIDATE_VALUES (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CLAIM_ID VARCHAR(255) NOT NULL,
	CALL_ID VARCHAR(255) NOT NULL,
	FIELD_NAME VARCHAR(255) NOT NULL,
	CANDIDATE_VALUE VARCHAR(16777216) NOT NULL,
	CONTEXT_TRANSCRIPT VARCHAR(16777216) NOT NULL,
	TRANSCRIPT_TIMESTAMP TIMESTAMP_NTZ(9) NOT NULL,
	IS_SELECTED BOOLEAN DEFAULT FALSE,
	SELECTED_BY VARCHAR(255),
	SELECTED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	primary key (ID),
	index IDX_CLAIM_CANDIDATE(CLAIM_ID),
	index IDX_FIELD_CANDIDATE(FIELD_NAME),
	index IDX_SELECTED(IS_SELECTED)
);